language: python
python:
  - "3.8"
services:
  - postgresql
env:
  global:
    - PGPORT=5433
    - DB_NAME=testflaskapp
    - DB_USER=postgres
    - DB_PASSWORD=postgres
before_script:
  - psql -c 'create database testflaskapp;' -U postgres
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run -m unittest discover tests/rest/
  - coverage run -m unittest discover tests/noapi/
after_success:
  - coveralls