language: python
python:
  - "3.8"
<<<<<<< HEAD
=======
services:
  - postgresql
env:
  global:
    - DB_NAME=testflaskapp
    - DB_USER=postgres
    - DB_PASSWORD=postgres
    - SECRET_KEY=45t82hfmieuvf5984nyuru84ty34htejhiuyj4382fu
before_script:
  - psql -c 'create database testflaskapp;' -U postgres
>>>>>>> main
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
<<<<<<< HEAD
  - pytest ...
  - coverage run --source=... pytest ...
=======
  - coverage run -m unittest discover tests/rest/
  - coverage run -m unittest discover tests/noapi/
>>>>>>> main
after_success:
  - coveralls