"""empty message

Revision ID: 302f6fb4b907
Revises: 2ead389c19e5
Create Date: 2021-12-19 16:03:07.669675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '302f6fb4b907'
down_revision = '2ead389c19e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_result_uuid'), 'result', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_uuid'), table_name='result')
    op.drop_column('result', 'uuid')
    # ### end Alembic commands ###
