"""empty message

Revision ID: 5b07cc2897c7
Revises: 946bec038ced
Create Date: 2021-12-11 23:50:45.592765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b07cc2897c7'
down_revision = '946bec038ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_post_uuid'), 'post', ['uuid'], unique=True)
    op.add_column('user', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_user_uuid'), 'user', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_uuid'), table_name='user')
    op.drop_column('user', 'uuid')
    op.drop_index(op.f('ix_post_uuid'), table_name='post')
    op.drop_column('post', 'uuid')
    # ### end Alembic commands ###
