"""empty message

Revision ID: ec9c5caacd96
Revises: 91b8633c51e1
Create Date: 2021-12-21 20:52:00.749047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9c5caacd96'
down_revision = '91b8633c51e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_test_id_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'test', ['test_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_test_id_fkey', 'post', 'test', ['test_id'], ['id'])
    # ### end Alembic commands ###
